### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by ratbunch** [bbilly1/media_organizer#3]
Just a warning to anyone that finds this through google. Not very stable. While it didn't delete my files it fails on the simplest of issues. Says its meant for linux but can't handle media files named on windows with spaces or other non standard characters. Which is basically how every single media file is named when you download it. I literally found this hoping it would rename files to follow linux naming conventions. Boy was I wrong.

It unpacks all your files and moves them to the sorted directory you set. Ok, but it does this ALL AT ONCE for every file and deletes the original folder structure. So I'm left with thousands of TV shows all sitting in a single folder with different naming conventions I gotta sort through now. Basically, this does the opposite of what its meant to do. I wouldn't even bother.

How it doesn't at the very least move files AFTER VERIFYING is beyond me. It failed on my first named file because it couldn't split a string correctly but thought it was a good idea to completely destroy the existing folder structure I had before even fixing one file name.

You've been warned.

**Comment by bbilly1** [comment]
You let a random script from the internet loose on thousands of your files without any kind of verification? No backup? Without checking the code? That's on you! Don't come here and blame anybody for that.

For what it's worth:
- It's clearly stated that this is linux only.
- This doesn't delete anything, this uses [trash-cli](https://github.com/bbilly1/media_organizer/blob/master/requirements.txt#L2). 
- Sort path is also mentioned in the readme
- It's also mentioned that some files might fail if there isn't enough info in the filename.

General rule of thumb when testing out software you found on random places on the internet:
- Obviously don't trust anything.
- Make a copy of your files first.
- Run it on a subset of files, like one folder, one season, see how it works and how it doesn't work as you expect.

If you have anything constructive to add like a PR to fix something, you are welcome to.
